name: Build ZFB
run-name: ${{ github.actor }}
on: [push]

jobs:
  Setup-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          cd ZFB
          git submodule update --init --recursive

      - run: |
          cd ZFB
          cmake -B build -DCMAKE_BUILD_TYPE=Release

      - run: |
          cd ZFB
          cmake --build build
